### ISSUE TITLE
Can't see mounted harddrive?

### ISSUE THREAD

**Issue by muntzstudios** [jcelaya/hdrmerge#186]
I've installed this software on my Mac ( current OS), and all I have access to is my home folder and the computer, and under the computer I only see 1x of the two drives on my imac (spite the fusion when I installed 2x solid state drives) and I do not see my mounted 20TB RAID drive

I need to process files on my external, how can I fix this?

**Comment by fanckush** [comment]
I think has been fixed with V1.0 when they moved from Qt4 to Qt5. You are probably using V0.5.0
To use V1.0 you have to build it yourself on macOS using the instructions here [INSTALL.md](https://github.com/jcelaya/hdrmerge/blob/master/INSTALL.md)

There are about 10 easy steps to follow. Let me know if you have trouble with building.

**Comment by muntzstudios** [comment]
I have zero experience with this, any chance you already have it built and I could use it haha?

**Comment by Benitoite** [comment]
There is one here you can try. 

https://keybase.pub/kd6kxr/HDRMerge-f74cf3d.dmg

**Comment by muntzstudios** [comment]
Great, thanks! I’ll give it a shot.

**Comment by fanckush** [comment]
@muntzstudios let us know once you try it if v1.0 fixes this issue so we could potentially add it to the changelog

**Comment by Beep6581** [comment]
Note that HDRMerge v1.0 has not been released yet, it does not exist. v0.5 was released in 2015 and there have been 140 commits since then, you're simply testing the latest development code which will become v1.0 in the near future.

**Comment by fanckush** [comment]
I think it's safe to assume it worked :)
