### ISSUE TITLE
Is this project ongoing? 

### ISSUE THREAD

**Issue by tpinfold** [jcelaya/hdrmerge#228]
CR3 file support is needed, but are there any developers still working on this project?

**Comment by ArchangeGabriel** [comment]
Honestly it does not seem so, last commit is more than two years old now, and the simple but mandatory #221 and #222 PR for building on modern distros have not been merged.

**Comment by ArchangeGabriel** [comment]
Oh, and the last release just went 9 years old, despite important work like moving from Qt4 to Qt5 already merged since.

**Comment by Entropy512** [comment]
There's some effort being put in, but not too much.  Probably needs a new maintainer.  I'm happy to contribute (and am working on some bugfixes), but I'm currently not in a situation where I should be taking on maintainer roles for anything.

Given that HDRMerge uses libraw and exiv2, rebuilding it against recent versions of either SHOULD work for CR3?  Metadata support might require a small code change since exiv2 defaults to disabling BMFF unless the application explicitly turns it on.  (which is a pain in the ass for application developers...)

**Comment by Beep6581** [comment]
I merged #221 and #222.

I would like to see a new version released as well. Please help by pointing out what needs doing. I am leaving for two weeks, and will take a look after I return. You can comment in #150
